//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDmvchim.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class detail
    {
        public int ID { get; set; }
        [Required]
        [StringLength(15, ErrorMessage = "Please enter a valid name")]
        public string firstname { get; set; }
        public string lastname { get; set; }
        [Required]
        public string email { get; set; }
        [Required]
        public Nullable<int> rollno { get; set; }
        [Required]
        public string student_address { get; set; }
        [Required]
        public string student_state { get; set; }
        [Required]
        
        public Nullable<int> mobile { get; set; }
    }
}
